backend:
  name: github
  repo: FrontMen/frontmania-2019
  branch: master

media_folder: 'static/uploads'
public_folder: '/uploads'

collections:
  - name: 'events'
    label: 'Events'
    folder: 'events'
    format: 'json'
    create: true
    slug: '{{slug}}'
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - {
          label: 'Type',
          name: 'type',
          widget: 'select',
          options: ['pubquiz', 'meetup', 'conference'],
          default: ['meetup'],
        }
      - { label: 'Date', name: 'date', widget: 'date' }
      - { label: 'Address', name: 'address', widget: 'string' }
      - { label: 'City', name: 'city', widget: 'string' }
      - { label: 'Link', name: 'link', widget: 'string' }
      - { label: 'Link text', name: 'linktext', widget: 'string' }
      - {
          label: 'Rotation angle',
          name: 'rotation',
          widget: 'select',
          options: ['1.5', '0', default: ['0']],
        }
      - {
          label: 'Color',
          name: 'color',
          widget: 'select',
          options: ['#ea5297', '#13a538'],
        }
  - name: 'speakers'
    label: 'Speakers'
    widget: 'object'
    folder: 'events'
    format: 'json'
    create: true
    slug: '{{slug}}'
    fields:
      - { label: 'Title', name: 'title', widget: 'string', default: 'FrontMania 2019 Speakers' }
      - label: 'Speaker_1'
        name: 'speaker_1'
        widget: 'object'
        fields:
          - {label: 'Name', name: 'name', widget: 'string', required: false}
          - {label: 'Twitter', name: 'twitter', widget: 'string',  required: false}
          - {label: 'Bio', name: 'bio', widget: 'text',  required: false}
          - {label: 'Image', name: 'imgurl', widget: 'text',  required: false}
          - {label: 'Talk Title', name: 'talkTitle', widget: 'string',  required: false}
          - {label: 'Talk Description', name: 'talkDescription', widget: 'text',  required: false}

      - label: 'Speaker_2'
        name: 'speaker_2'
        widget: 'object'
        fields:
          - {label: 'Name', name: 'name', widget: 'string',  required: false}
          - {label: 'Twitter', name: 'twitter', widget: 'string',  required: false}
          - {label: 'Bio', name: 'bio', widget: 'text',  required: false}
          - {label: 'Image', name: 'imgurl', widget: 'text',  required: false}
          - {label: 'Talk Title', name: 'talkTitle', widget: 'string',  required: false}
          - {label: 'Talk Description', name: 'talkDescription', widget: 'text',  required: false}

      - label: 'Speaker_3'
        name: 'speaker_3'
        widget: 'object'
        fields:
          - {label: 'Name', name: 'name', widget: 'string',  required: false}
          - {label: 'Twitter', name: 'twitter', widget: 'string',  required: false}
          - {label: 'Bio', name: 'bio', widget: 'text',  required: false}
          - {label: 'Image', name: 'imgurl', widget: 'text',  required: false}
          - {label: 'Talk Title', name: 'talkTitle', widget: 'string',  required: false}
          - {label: 'Talk Description', name: 'talkDescription', widget: 'text',  required: false}

      - label: 'Speaker_4'
        name: 'speaker_4'
        widget: 'object'
        fields:
          - {label: 'Name', name: 'name', widget: 'string',  required: false}
          - {label: 'Twitter', name: 'twitter', widget: 'string',  required: false}
          - {label: 'Bio', name: 'bio', widget: 'text',  required: false}
          - {label: 'Image', name: 'imgurl', widget: 'text',  required: false}
          - {label: 'Talk Title', name: 'talkTitle', widget: 'string',  required: false}
          - {label: 'Talk Description', name: 'talkDescription', widget: 'text',  required: false}

      - label: 'Speaker_5'
        name: 'speaker_5'
        widget: 'object'
        fields:
          - {label: 'Name', name: 'name', widget: 'string',  required: false}
          - {label: 'Twitter', name: 'twitter', widget: 'string',  required: false}
          - {label: 'Bio', name: 'bio', widget: 'text',  required: false}
          - {label: 'Image', name: 'imgurl', widget: 'text',  required: false}
          - {label: 'Talk Title', name: 'talkTitle', widget: 'string',  required: false}
          - {label: 'Talk Description', name: 'talkDescription', widget: 'text',  required: false}

      - label: 'Speaker_6'
        name: 'speaker_6'
        widget: 'object'
        fields:
          - {label: 'Name', name: 'name', widget: 'string',  required: false}
          - {label: 'Twitter', name: 'twitter', widget: 'string',  required: false}
          - {label: 'Bio', name: 'bio', widget: 'text',  required: false}
          - {label: 'Image', name: 'imgurl', widget: 'text',  required: false}
          - {label: 'Talk Title', name: 'talkTitle', widget: 'string',  required: false}
          - {label: 'Talk Description', name: 'talkDescription', widget: 'text',  required: false}

      - label: 'Speaker_7'
        name: 'speaker_7'
        widget: 'object'
        fields:
          - {label: 'Name', name: 'name', widget: 'string',  required: false}
          - {label: 'Twitter', name: 'twitter', widget: 'string',  required: false}
          - {label: 'Bio', name: 'bio', widget: 'text',  required: false}
          - {label: 'Image', name: 'imgurl', widget: 'text',  required: false}
          - {label: 'Talk Title', name: 'talkTitle', widget: 'string',  required: false}
          - {label: 'Talk Description', name: 'talkDescription', widget: 'text',  required: false}

      - label: 'Speaker_8'
        name: 'speaker_8'
        widget: 'object'
        fields:
          - {label: 'Name', name: 'name', widget: 'string',  required: false}
          - {label: 'Twitter', name: 'twitter', widget: 'string',  required: false}
          - {label: 'Bio', name: 'bio', widget: 'text',  required: false}
          - {label: 'Image', name: 'imgurl', widget: 'text',  required: false}
          - {label: 'Talk Title', name: 'talkTitle', widget: 'string',  required: false}
          - {label: 'Talk Description', name: 'talkDescription', widget: 'text',  required: false}

      - label: 'Speaker_9'
        name: 'speaker_9'
        widget: 'object'
        fields:
          - {label: 'Name', name: 'name', widget: 'string',  required: false}
          - {label: 'Twitter', name: 'twitter', widget: 'string',  required: false}
          - {label: 'Bio', name: 'twitter', widget: 'text',  required: false}
          - {label: 'Image', name: 'imgurl', widget: 'text',  required: false}
          - {label: 'Talk Title', name: 'talkTitle', widget: 'string',  required: false}
          - {label: 'Talk Description', name: 'talkDescription', widget: 'text',  required: false}

      - label: 'Speaker_10'
        name: 'speaker_10'
        widget: 'object'
        fields:
          - {label: 'Name', name: 'name', widget: 'string',  required: false}
          - {label: 'Twitter', name: 'twitter', widget: 'string',  required: false}
          - {label: 'Bio', name: 'bio', widget: 'text',  required: false}
          - {label: 'Image', name: 'imgurl', widget: 'text',  required: false}
          - {label: 'Talk Title', name: 'talkTitle', widget: 'string',  required: false}
          - {label: 'Talk Description', name: 'talkDescription', widget: 'text',  required: false}

      - label: 'Speaker_11'
        name: 'speaker_11'
        widget: 'object'
        fields:
          - {label: 'Name', name: 'name', widget: 'string',  required: false}
          - {label: 'Twitter', name: 'twitter', widget: 'string',  required: false}
          - {label: 'Bio', name: 'bio', widget: 'text',  required: false}
          - {label: 'Image', name: 'imgurl', widget: 'text',  required: false}
          - {label: 'Talk Title', name: 'talkTitle', widget: 'string',  required: false}
          - {label: 'Talk Description', name: 'talkDescription', widget: 'text',  required: false}

      - label: 'Speaker_12'
        name: 'speaker_12'
        widget: 'object'
        fields:
          - {label: 'Name', name: 'name', widget: 'string',  required: false}
          - {label: 'Twitter', name: 'twitter', widget: 'string',  required: false}
          - {label: 'Bio', name: 'bio', widget: 'text',  required: false}
          - {label: 'Image', name: 'imgurl', widget: 'text',  required: false}
          - {label: 'Talk Title', name: 'talkTitle', widget: 'string',  required: false}
          - {label: 'Talk Description', name: 'talkDescription', widget: 'text',  required: false}

      - label: 'Speaker_13'
        name: 'speaker_13'
        widget: 'object'
        fields:
          - {label: 'Name', name: 'name', widget: 'string',  required: false}
          - {label: 'Twitter', name: 'twitter', widget: 'string',  required: false}
          - {label: 'Bio', name: 'bio', widget: 'text',  required: false}
          - {label: 'Image', name: 'imgurl', widget: 'text',  required: false}
          - {label: 'Talk Title', name: 'talkTitle', widget: 'string',  required: false}
          - {label: 'Talk Description', name: 'talkDescription', widget: 'text',  required: false}

      - label: 'Speaker_14'
        name: 'speaker_14'
        widget: 'object'
        fields:
          - {label: 'Name', name: 'name', widget: 'string',  required: false}
          - {label: 'Twitter', name: 'twitter', widget: 'string',  required: false}
          - {label: 'Bio', name: 'bio', widget: 'text',  required: false}
          - {label: 'Image', name: 'imgurl', widget: 'text',  required: false}
          - {label: 'Talk Title', name: 'talkTitle', widget: 'string',  required: false}
          - {label: 'Talk Description', name: 'talkDescription', widget: 'text',  required: false}

      - label: 'Speaker_15'
        name: 'speaker_5'
        widget: 'object'
        fields:
          - {label: 'Name', name: 'name', widget: 'string',  required: false}
          - {label: 'Twitter', name: 'twitter', widget: 'string',  required: false}
          - {label: 'Bio', name: 'bio', widget: 'text',  required: false}
          - {label: 'Image', name: 'imgurl', widget: 'text',  required: false}
          - {label: 'Talk Title', name: 'talkTitle', widget: 'string',  required: false}
          - {label: 'Talk Description', name: 'talkDescription', widget: 'text',  required: false}

      - label: 'Speaker_16'
        name: 'speaker_16'
        widget: 'object'
        fields:
          - {label: 'Name', name: 'name', widget: 'string',  required: false}
          - {label: 'Twitter', name: 'twitter', widget: 'string',  required: false}
          - {label: 'Bio', name: 'bio', widget: 'text',  required: false}
          - {label: 'Image', name: 'imgurl', widget: 'text',  required: false}
          - {label: 'Talk Title', name: 'talkTitle', widget: 'string',  required: false}
          - {label: 'Talk Description', name: 'talkDescription', widget: 'text',  required: false}

      - label: 'Speaker_17'
        name: 'speaker_17'
        widget: 'object'
        fields:
          - {label: 'Name', name: 'name', widget: 'string',  required: false}
          - {label: 'Twitter', name: 'twitter', widget: 'string',  required: false}
          - {label: 'Bio', name: 'bio', widget: 'text',  required: false}
          - {label: 'Image', name: 'imgurl', widget: 'text',  required: false}
          - {label: 'Talk Title', name: 'talkTitle', widget: 'string',  required: false}
          - {label: 'Talk Description', name: 'talkDescription', widget: 'text',  required: false}

      - label: 'Speaker_18'
        name: 'speaker_18'
        widget: 'object'
        fields:
          - {label: 'Name', name: 'name', widget: 'string',  required: false}
          - {label: 'Twitter', name: 'twitter', widget: 'string',  required: false}
          - {label: 'Bio', name: 'bio', widget: 'text',  required: false}
          - {label: 'Image', name: 'imgurl', widget: 'text',  required: false}
          - {label: 'Talk Title', name: 'talkTitle', widget: 'string',  required: false}
          - {label: 'Talk Description', name: 'talkDescription', widget: 'text',  required: false}

      - label: 'Speaker_19'
        name: 'speaker_19'
        widget: 'object'
        fields:
          - {label: 'Name', name: 'name', widget: 'string',  required: false}
          - {label: 'Twitter', name: 'twitter', widget: 'string',  required: false}
          - {label: 'Bio', name: 'bio', widget: 'text',  required: false}
          - {label: 'Image', name: 'imgurl', widget: 'text',  required: false}
          - {label: 'Talk Title', name: 'talkTitle', widget: 'string',  required: false}
          - {label: 'Talk Description', name: 'talkDescription', widget: 'text',  required: false}

      - label: 'Speaker_20'
        name: 'speaker_20'
        widget: 'object'
        fields:
          - {label: 'Name', name: 'name', widget: 'string',  required: false}
          - {label: 'Twitter', name: 'twitter', widget: 'string',  required: false}
          - {label: 'Bio', name: 'bio', widget: 'text',  required: false}
          - {label: 'Image', name: 'imgurl', widget: 'text',  required: false}
          - {label: 'Talk Title', name: 'talkTitle', widget: 'string',  required: false}
          - {label: 'Talk Description', name: 'talkDescription', widget: 'text',  required: false}

  - name: 'schedule'
    label: 'Schedule'
    folder: 'schedule'
    format: 'json'
    create: true
    slug: '{{slug}}'
    identifier_field: name
    fields:
      - { label: 'Title', name: 'title', widget: 'string', default: 'FrontMania 2019 Schedule' }
      - label: 'Events'
        name: 'events'
        widget: 'object'
        fields:
          - label: '09:00 - 09:30'
            name: '0900-0930'
            widget: 'object'
            fields:
              - label: 'Track 1'
                name: 'track_1'
                widget: 'relation'
                collection: 'speakers'
                valueField: 'speakers.name.name'
                searchFields: ['name']
              - label: 'Track 2'
                name: 'track_2'
                widget: 'relation'
                collection: 'speakers'
                valueField: 'speakers.name.name'
                searchFields: ['name']
          - label: '09:30 - 10:30'
            name: '0930-1030'
            widget: 'object'
            fields:
              - label: 'Track 1'
                name: 'track_1'
                widget: 'relation'
                collection: 'speakers'
                valueField: 'speakers.name.name'
                searchFields: ['name']
              - label: 'Track 2'
                name: 'track_2'
                widget: 'relation'
                collection: 'speakers'
                valueField: 'speakers.name.name'
                searchFields: ['name']
